export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';